server:
  address: 0.0.0.0
  servlet:
    context-path: /api
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

spring:
  application:
    name: realtime-chat-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_db}
    username: ${DB_USER:chat_user}
    password: ${DB_PASSWORD:chat_password}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public

jwt:
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:P7D}
  secret: ${JWT_SECRET:ZS87ZzFBP43UyPcy1BH/4SHLbXHvvTLxZKQa/x7vwh26XyamkeIGSrmVbzhVvO7+}
  pepper: ${JWT_PEPPER:mUeaEJTkndKbKpRAIk8R0h7DL5zeUxHHIXRDdE4frvcIWPjpgxkQg5HHzOIC2phl}
